@SelfOnBoarding

Feature: OnBoarding New Merchant Choose POS Option

  Background:
    Given The webBrowser is launched

  Scenario Outline: "<ScenarioDescription>"
    Given I am on the merchant landing page "<ScenarioDescription>""<reportName>""<landingPage>""<reportAuthor>""<landingPageSuccess>"
    And I Choose Available POS Option "<deviceOption>"
    And Submit Merchant details "<ownershipDetails>" "<firstName>" "<surName>" "<eMail>" "<mobileNo>" "<idType>" "<idNo>" "<inputBusinessStreetName>" "<businessStreetName>" "<businessPostalCode>" "<businessSuburb>" "<businessTown>" "<Province>" "<journey_name>"
    And I Then Assign Device and Process Order "<deviceReceiptOption>" "<devicePaymentOption>" "<journey_name>"
    And I populate VPG Payment Details "<devicePaymentOption>"
    And I select immediate payment method "<onceNameOnCard>""<onceCardNo>""<onceExpireYear>""<onceExpiryDate>""<onceCvv>""<devicePaymentOption>"
    And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    And Start Setup Customer Account Landing Page
    And FICA PROCESS Pages Tell Us About The Customers Business "<companyTypeOption>" "<companyRegName>" "<businessMonthlIncome>" "<businessCategory>" "<AddressYearMonthDayStayed>"
    And FICA PROCESS Pages Confirm the customers personal details "<ownershipDetails>" "<firstName>" "<surName>"
    And FICA PROCESS Pages Confirm the customers banking details "<bankName>" "<idNo>" "<account_number>" "<firstName>" "<surName>"
    And I take a selfie
    And I  upload documents "<companyTypeOption>""<idDocumentType>"
    And I close all browser

      #And I Then Complete Device Order
       #And I close ThreeD tab "<devicePaymentOption>""<bankName>"
    #And I Check Payment Status "<devicePaymentOption>""<bankName>"
    #And I populate VPG Payment Details "<onceNameOnCard>" "<onceCardNo>" "<onceExpireYear>" "<onceExpiryDate>" "<onceCvv>"
   # And I populate Bank Card Details "<onceNameOnCard>" "<onceCardNo>" "<onceExpireYear>" "<onceExpiryDate>" "<onceCvv>"
   # And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    #And I take a selfie
    #And I  upload documents "<companyTypeOption>""<idDocumentType>"


      #And I Provide Company and Personal Details "<companyTypeOption>" "<monthlyIncomeKnowledge>" "<businessMonthlIncome>" "<companyRegName>" "<companyDifferentName>" "<companyRegNo>" "<businessCategory>" "<companyTradingName>"
    #And I take a selfie
    #And I  upload documents "<companyTypeOption>""<idDocumentType>"
    #And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    #And I Provide Company Details "<companyTypeOption>" "<companyRegName>" "<companyDifferentName>" "<monthlyIncomeKnowledge>" "<businessMonthlIncome>" "<businessCategory>" "<companyRegNo>" "<companyTradingName>"
    #And I Provide Company and Personal Details "<companyTypeOption>" "<monthlyIncomeKnowledge>" "<businessMonthlIncome>" "<companyRegName>" "<companyDifferentName>" "<companyRegNo>" "<businessCategory>" "<companyTradingName>"
    #And I Provide the Partners Details "<companyTypeOption>""<partnersID>"
    #And I Provide the Banking Details "<companyTypeOption>" "<accountName>" "<accountNumber>"



    Examples:
      | TC | ScenarioDescription                          | ScenarioType | reportName           | landingPage       | reportAuthor      | landingPageSuccess | dealer | userId  | password      | deviceOption                                                                       | merchantId      | passWord   | ownershipDetails        | firstName | surName | eMail                                  | mobileNo   | idType        | idNo          | idDocumentType | inputBusinessStreetName | businessStreetName     | businessPostalCode | businessSuburb   | businessTown | Province | deviceReceiptOption | devicePaymentOption | companyTypeOption   | companyRegName      | companyDifferentName | monthlyIncomeKnowledge | businessMonthlIncome | companyTradingName   | companyRegNo | businessCategory       | partnersID    | accountName    | accountNumber | onceNameOnCard | onceCardNo       | onceExpireYear | onceExpiryDate | onceCvv | threeDPassword | cardType | bankName      | AddressYearMonthDayStayed | account_number | journey_name    | Barcode Number |
      | 1  | Makro selects Kwika                          | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Kwika                                                                      | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      | 2  | Makro selects Max                            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Max                                                                        | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      | 3  | Makro selects Kwika with All virtual Devices | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Kwika,VodaPay Tap on Phone,VodaPay Payment Gateway,VodaPay Payment Request | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      | 4  | Makro selects All virtual Devices            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Tap on Phone,VodaPay Payment Gateway,VodaPay Payment Request               | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      | 5  | Makro selects VPG                            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Payment Gateway                                                            | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      | 6  | Makro selects VPR                            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Payment Request                                                            | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      | 7  | Makro selects Tap on Phone                   | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Tap on Phone                                                               | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
