@thirdPartyOnboardingPaymentRequest

Feature: third Party Login

  Background:
  #  Given The webBrowser is launched
    Given The webBrowser is launched

  Scenario Outline: "<ScenarioDescription>"
    And I am on the dealer landing page "<ScenarioDescription>""<reportName>""<landingPage>""<reportAuthor>""<landingPageSuccess>"
    And When I select Dealer "<dealer>""<userId>""<password>"
    And I Choose Available POS Option "<deviceOption>"
    And Submit Merchant details "<ownershipDetails>" "<firstName>" "<surName>" "<eMail>" "<mobileNo>" "<idType>" "<idNo>" "<inputBusinessStreetName>" "<businessStreetName>" "<businessPostalCode>" "<businessSuburb>" "<businessTown>" "<Province>"
    And I Then Assign Device and Process Order "<deviceReceiptOption>" "<devicePaymentOption>"
    And I verify Payment Request Link and complete payment "<devicePaymentOption>"
    And I select immediate payment method "<onceNameOnCard>""<onceCardNo>""<onceExpireYear>""<onceExpiryDate>""<onceCvv>""<devicePaymentOption>"
    And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    And I close ThreeD tab "<devicePaymentOption>""<bankName>"
    And I Check Payment Status "<devicePaymentOption>""<bankName>"
    And Start Setup Customer Account Landing Page
    And FICA PROCESS Pages Tell Us About The Customers Business "<companyTypeOption>" "<companyRegName>" "<businessMonthlIncome>" "<businessCategory>" "<AddressYearMonthDayStayed>"
    And FICA PROCESS Pages Confirm the customers personal details "<ownershipDetails>" "<firstName>" "<surName>"
    And FICA PROCESS Pages Confirm the customers banking details <bankName>" "<firstName>" "<surName>"
   # And I take a selfie
    #And I  upload documents "<companyTypeOption>""<idDocumentType>"


    #And I populate Once Card Details "<onceNameOnCard>""<onceCardNo>""<onceExpireYear>""<onceExpiryDate>""<onceCvv>"

    #And I Provide the Banking Details "<companyTypeOption>" "<accountName>" "<accountNumber>"
    #And I populate Once Card Details "<onceNameOnCard>""<onceCardNo>""<onceExpireYear>""<onceExpiryDate>""<onceCvv>"
    #And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    #And I select ECom Response URL and decode Bank Response URL "Approved or completed successfully""<ExpectedMessage>"
    #And I must assert card transaction message "Approved or completed successfully""<ExpectedMessage>" and report

    Examples:
      | TC | ScenarioDescription                                      | ScenarioType | reportName           | landingPage | reportAuthor      | landingPageSuccess | dealer | userId  | password      | deviceOption                                                                                   | merchantId      | passWord   | ownershipDetails        | firstName | surName | eMail                                  | mobileNo   | idType        | idNo          | idDocumentType | inputBusinessStreetName | businessStreetName     | businessPostalCode | businessSuburb   | businessTown | Province | deviceReceiptOption | devicePaymentOption | companyTypeOption   | companyRegName      | companyDifferentName | monthlyIncomeKnowledge | businessMonthlIncome | companyTradingName   | companyRegNo | businessCategory       | partnersID    | accountName    | accountNumber | onceNameOnCard | onceCardNo       | onceExpireYear | onceExpiryDate | onceCvv | threeDPassword | cardType | bankName      | AddressYearMonthDayStayed |
      #| 1  | Third Party Makro Dealer login                  | Positive     | Makro dealer journey | 3poURL      | Itumeleng Phale   |                    | Makro  | Shubham  | Traderoot123!    | VodaPay Kwika                                                                                  | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 4923050000060310 | 2027           | March          | 661     | test123        | Physical | Nedbank Debit |
      #| 2  | Third Party Game Dealer login                   | Positive     | Game dealer journey  | 3poURL      | Tebello Ntyingila |                    | Game   | Junius01 | Testing@123      | VodaPay Kwika                                                                                  | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | Cash                | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 5413330089010483 | 2024           | September      | 946     | test123        | Physical | Nedbank Debit |
      | 3  | Markro selects Physical Devices with all Virtual payment | Positive     | Makro dealer journey | 3poURL      | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Kwika,VodaPay Tap on Phone,VodaPay Payment Gateway,VodaPay Payment Request,VodaPay Max | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | nervous-strange@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 5181030000959467 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                |
      #| 4  | Kwika Journey                                   | Positive     | Game dealer journey  | 3poURL      | Tebello Ntyingila |                    | Game   | Junius01 | Testing@123      | VodaPay Kwika                                                                                  | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | Cash                | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 5413330089010483 | 2024           | September      | 946     | test123        | Physical | Nedbank Debit |
      #| 4  | Kwika Journey                                   | Positive     | Game dealer journey  | 3poURL      | Tebello Ntyingila |                    | Game   | Junius01 | Testing@123      | VodaPay Tap on Phone                                                                           | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | Cash                | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 5413330089010483 | 2024           | September      | 946     | test123        | Physical | Nedbank Debit |
      #| 4  | Kwika Journey                                   | Positive     | Game dealer journey  | 3poURL      | Tebello Ntyingila |                    | Game   | Junius01 | Testing@123      | VodaPay Payment Gateway                                                                        | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | Cash                | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 5413330089010483 | 2024           | September      | 946     | test123        | Physical | Nedbank Debit |
      #| 4  | Kwika Journey                                   | Positive     | Game dealer journey  | 3poURL      | Tebello Ntyingila |                    | Game   | Junius01 | Testing@123      | VodaPay Payment Request                                                                        | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | Cash                | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 5413330089010483 | 2024           | September      | 946     | test123        | Physical | Nedbank Debit |
      #| 4  | Kwika Journey                                   | Positive     | Game dealer journey  | 3poURL      | Tebello Ntyingila |                    | Game   | Junius01 | Testing@123      | VodaPay Max                                                                                    | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | officer-most@2mk3aglp.mailosaur.net | 0833721854 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | Cash                | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | Itumeleng Testing SMME | 5413330089010483 | 2024           | September      | 946     | test123        | Physical | Nedbank Debit |

      #| 2  | Third Party Game Dealer login  | Positive     | Game dealer journey  | 3poURL      | VFS Tester      |                    | Game                | Junius01 | Testing@123 | VodaPay Kwika | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | vfsautomator@gmail.com | 0829973883 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent | 0157               | Amberville     | Centurion    | Gauteng  | smsReCeipt          | payFlex             | Sole Proprietorship | VFS Payment Testing | No                   | Yes                    | 12000                | Payments Test Team   | 123456789012 | Agricultural Cooperatives | 6508267473086 | VFS Automators | 1234567890    |
      #| 3  | 3PO Vodacom Store Dealer login | Positive     | Vodacom Store Agent  | 3poURL      | VFS Tester      |                    | Vodacom Store Agent | Mooimots | Change@123  | VodaPay Kwika | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | vfsautomator@gmail.com | 0829973883 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent | 0157               | Amberville     | Centurion    | Gauteng  | smsReCeipt          | payFlex             | Sole Proprietorship | VFS Payment Testing | No                   | Yes                    | 12000                | Payments Test Team   | 123456789012 | Agricultural Cooperatives | 6508267473086 | VFS Automators | 1234567890    |
      #| 3  | Third Party Dealer login | Positive     | One Source Direct | 3poURL      | Itumeleng Phale |                    | Makro  | Shubham | Testing@123 | VodaPay Kwika | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | livhuwani.mutshafa@vcontractor.co.za | 0829973883 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent | 0157               | Amberville     | Centurion    | Gauteng  | Trust             | No                     | 150000               | IBP Testing VFS | Yes                  | Ditekong Software Testing | 123456789012 | Agricultural Cooperatives | 6508267473086 | TM Ngwane   | 1234567890    |
      #| 4  | Third Party Dealer login | Positive     | SMME Onboarding | 3poURL      | Itumeleng Phale |                    | Makro  | Shubham | Testing@123 | VodaPay Kwika | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | livhuwani.mutshafa@vcontractor.co.za | 0829973883 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent | 0157               | Amberville     | Centurion    | Gauteng  | Trust             | No                     | 150000               | IBP Testing VFS | Yes                  | Ditekong Software Testing | 123456789012 | Agricultural Cooperatives | 6508267473086 | TM Ngwane   | 1234567890    |
      #| 5  | Third Party Dealer login | Positive     | Vodacom Store Agent | 3poURL      | Itumeleng Phale |                    | Makro  | Shubham | Testing@123 | VodaPay Kwika | VPS983577986487 | 143@Mayoga | Business owner/director | Ecomm Automator | VFS Ecomm | livhuwani.mutshafa@vcontractor.co.za | 0829973883 | South African | 9509040030083 | green card     | 4586 Isacholo Crescent | 0157               | Amberville     | Centurion    | Gauteng  | Trust             | No                     | 150000               | IBP Testing VFS | Yes                  | Ditekong Software Testing | 123456789012 | Agricultural Cooperatives | 6508267473086 | TM Ngwane   | 1234567890    |
