@selfOnBoarding

Feature: OnBoarding New Merchant Choose POS Option

  Background:
    Given The webBrowser is launched

  Scenario Outline: "<ScenarioDescription>"
    Given I am on the merchant landing page "<ScenarioDescription>""<reportName>""<landingPage>""<reportAuthor>""<landingPageSuccess>"
    #And Start Setup Environment
    And I Choose Available POS Option "<deviceOption>"
    And Submit Personal Details "<firstName>" "<surName>" "<eMail>" "<mobileNo>"
    And I select immediate payment method "<onceCardNo>""<onceExpiryDate>""<onceExpireYear>""<onceCvv>""<onceNameOnCard>""<devicePaymentOption>"
    And I choose ThreeD Secure Option
    And I upload ID documents "<idDocumentType>"
    And I take a selfie
    And Submit business details "<ownershipDetails>" "<title>" "<idNo>" "<companyRegName>" "<businessCategory>" "<inputBusinessStreetName>" "<businessAdress>"
    And Submit Bank Details "<bankName>""<accountType>""<accountNumber>"
    #And Submit delivery details "<buildingType>" "<inputBusinessStreetName>" "<businessStreetName>" "<businessPostalCode>" "<businessSuburb>" "<businessTown>" "<Province>" "<businessAdress>" "<journey_name>"
    #And Submit Merchant details SF Confirmation "<ownershipDetails>" "<firstName>" "<surName>" "<eMail>" "<mobileNo>" "<idType>" "<idNo>" "<inputBusinessStreetName>" "<businessStreetName>" "<businessPostalCode>" "<businessSuburb>" "<businessTown>" "<Province>" "<journey_name>"
    #And I Then Assign Device and Process Order "<deviceReceiptOption>" "<devicePaymentOption>" "<journey_name>"
    #And I Then Assign Device and Process Order SF Confirmation "<deviceReceiptOption>" "<devicePaymentOption>" "<journey_name>"
    #And I populate VPG Payment Details "<devicePaymentOption>"
    # And I select immediate payment method "<onceNameOnCard>""<onceCardNo>""<onceExpireYear>""<onceExpiryDate>""<onceCvv>""<devicePaymentOption>"
    #And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    #And Start Setup Customer Account Landing Page
    #And FICA PROCESS Pages Tell Us About The Customers Business "<companyTypeOption>" "<companyRegName>" "<businessMonthlIncome>" "<businessCategory>" "<AddressYearMonthDayStayed>"
    #And FICA PROCESS Pages Confirm the customers personal details "<ownershipDetails>" "<firstName>" "<surName>"
    #And FICA PROCESS Pages Confirm the customers banking details "<bankName>" "<idNo>" "<account_number>" "<firstName>" "<surName>"
    #And I Disable SMME DevTools Proof of Life
    #And I take a selfie
    #And I  upload documents "<companyTypeOption>""<idDocumentType>"
    #And I close all browser

      #And I Then Complete Device Order
       #And I close ThreeD tab "<devicePaymentOption>""<bankName>"
    #And I Check Payment Status "<devicePaymentOption>""<bankName>"
    #And I populate VPG Payment Details "<onceNameOnCard>" "<onceCardNo>" "<onceExpireYear>" "<onceExpiryDate>" "<onceCvv>"
   # And I populate Bank Card Details "<onceNameOnCard>" "<onceCardNo>" "<onceExpireYear>" "<onceExpiryDate>" "<onceCvv>"
   # And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    #And I take a selfie
    #And I  upload documents "<companyTypeOption>""<idDocumentType>"


      #And I Provide Company and Personal Details "<companyTypeOption>" "<monthlyIncomeKnowledge>" "<businessMonthlIncome>" "<companyRegName>" "<companyDifferentName>" "<companyRegNo>" "<businessCategory>" "<companyTradingName>"
    #And I take a selfie
    #And I  upload documents "<companyTypeOption>""<idDocumentType>"
    #And I Populate ThreeD Secure "<threeDPassword>""<cardType>""<bankName>"
    #And I Provide Company Details "<companyTypeOption>" "<companyRegName>" "<companyDifferentName>" "<monthlyIncomeKnowledge>" "<businessMonthlIncome>" "<businessCategory>" "<companyRegNo>" "<companyTradingName>"
    #And I Provide Company and Personal Details "<companyTypeOption>" "<monthlyIncomeKnowledge>" "<businessMonthlIncome>" "<companyRegName>" "<companyDifferentName>" "<companyRegNo>" "<businessCategory>" "<companyTradingName>"
    #And I Provide the Partners Details "<companyTypeOption>""<partnersID>"
    #And I Provide the Banking Details "<companyTypeOption>" "<accountName>" "<accountNumber>"



    Examples:
      | TC | ScenarioDescription | ScenarioType | reportName           | landingPage       | reportAuthor      | landingPageSuccess | dealer | userId  | password      | deviceOption     | merchantId      | passWord   | ownershipDetails        | firstName | surName | eMail                               | mobileNo   | idType        | idNo          | idDocumentType | inputBusinessStreetName | businessStreetName     | businessPostalCode | businessSuburb   | businessTown | Province | deviceReceiptOption | devicePaymentOption | companyTypeOption   | companyRegName      | companyDifferentName | monthlyIncomeKnowledge | businessMonthylIncome | companyTradingName   | companyRegNo | businessCategory       | partnersID    | accountName    | accountNumber | onceNameOnCard | onceCardNo       | onceExpireYear | onceExpiryDate | onceCvv | threeDPassword | cardType | bankName | AddressYearMonthDayStayed | account_number | journey_name    | Barcode Number | accountType            | buildingType | businessAdress |  businessName | monthlyPayment | businessUrl | accountType|title|
      | 1  | Makro selects Kwika | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! |VodaPay Kwika[1] | VPS983577986487 | 143@Mayoga | Business owner/director | ASANDA    | KHUMALO |needle-early@olieygik.mailosaur.net | 0606799922 | South African | 8902210085089 | South African ID card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1010340824    | NONDIPHA LOUW  | 5181030000090396  | 2029          | 02             | 764     | test123        | Physical | Nedbank  | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    | Current Cheque Account | House        | My business address is the same as my trading address | null| null| null| null | Miss |
      #| 2  | Makro selects Max Buy| Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! |VodaPay Max[1]| VPS983577986487 | 143@Mayoga | Business owner/director | ASANDA    | KHUMALO | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 8902210085089 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1010340824    | NONDIPHA LOUW  | 4922130001585845 | 2027          | 03             | 904     | test123        | Physical | Nedbank  | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    | Current Cheque Account | House        | My business address is the same as my trading address | null| null| null| null |Miss |
      #| 3  | Makro selects N82 | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! |VodaPay Max[1] | VPS983577986487 | 143@Mayoga | Business owner/director | ASANDA    | KHUMALO | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 8902210085089 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1010340824    | NONDIPHA LOUW  | 4922130001585845 | 2027          | 03             | 904     | test123        | Physical | Nedbank  | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    | Current Cheque Account | House        | My business address is the same as my trading address | null| null| null| null |




      #| 4  | Makro selects VPG | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! |VodaPay Max[1] | VPS983577986487 | 143@Mayoga | Business owner/director | ASANDA    | KHUMALO | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 8902210085089 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1010340824    | NONDIPHA LOUW  | 4922130001585845 | 2027          | 03             | 904     | test123        | Physical | Nedbank  | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    | Current Cheque Account | House        | My business address is the same as my trading address | null| null| null| null |
      #| 3  | Makro selects VPR  | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! |VodaPay Max[1] | VPS983577986487 | 143@Mayoga | Business owner/director | ASANDA    | KHUMALO | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 8902210085089 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1010340824    | NONDIPHA LOUW  | 4922130001585845 | 2027          | 03             | 904     | test123        | Physical | Nedbank  | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    | Current Cheque Account | House        | My business address is the same as my trading address | null| null| null| null |

     # | 2  | Makro selects Kwika | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Payment Gateway[4]                                                                     | VPS983577986487 | 143@Mayoga | Business owner/director | ASANDA  | KHUMALO    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 8902210085089 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1010340824    | NONDIPHA LOUW  | 5120350100064594 | 2026           | May       | 855     | test123        | Physical | Nedbank | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    | VFS     | 1500  | http://vodacom.com | Current Cheque Account|

      #| 2  | Makro selects Max                            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Max                                                                        | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 377121700266462 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      #| 3  | Makro selects Kwika with All virtual Devices | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Kwika,VodaPay Tap on Phone,VodaPay Payment Gateway,VodaPay Payment Request | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 377121700266462 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      #| 4  | Makro selects All virtual Devices            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Tap on Phone,VodaPay Payment Gateway,VodaPay Payment Request               | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 377121700266462 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      #| 5  | Makro selects VPG                            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Payment Gateway                                                            | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 377121700266462 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      #| 6  | Makro selects VPR                            | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Payment Request                                                            | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 377121700266462 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
      #| 7  | Makro selects Tap on Phone                   | Positive     | Makro dealer journey | smmeOnboardingURL | Tebello Ntyingila |                    | Makro  | Shubham | Traderoot123! | VodaPay Tap on Phone                                                               | VPS983577986487 | 143@Mayoga | Business owner/director | NONDIPHA  | LOUW    | needle-early@olieygik.mailosaur.net | 0833721854 | South African | 6807015897087 | green card     | 4586 Isacholo Crescent  | 4586 Isacholo Crescent | 0187               | Blue Golf Estate | Centurion    | Gauteng  | emailReceipt        | cardPayment         | Sole Proprietorship | VFS Payment Testing | Yes                  | Yes                    | 15000                | VFS Software Testing | 123456789012 | Computer Software Shop | 6508267473086 | VFS Automators | 1234567890    | NONDIPHA LOUW  | 377121700266462 | 2029           | February       | 813     | test123        | Physical | Nedbank Debit | 2024-03-03                | 1288655444     | Self Onboarding | K3R0W007700    |
